title: "Uryu.log"
description: "秘密のサイトです^^決して口外しないこと"
url: "https://uyu77777.github.io"
baseurl: ""

markdown: kramdown
author: "kai"

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num"

sort: "date"
order: "descending"

