title: "Uryu.log"
description: "秘密のサイトです^^決して口外しないこと"
url: "https://uyu77777.github.io"
baseurl: ""

markdown: kramdown

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num"

author: "kai"

sort: 'date'
order: 'descending'

